<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MonoGame.Framework">
      <HintPath>C:\Users\User\Documents\GitHub\SDVios\lib\MonoGame.Framework.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="StardewModdingAPI">
      <HintPath>C:\Users\User\Desktop\SDVport Version\Game_Files\StardewModdingAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Stardew Valley">
      <HintPath>C:\Users\User\Desktop\SDVport Version\Game_Files\Stardew Valley.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>C:\Users\User\Desktop\SDVport Version\Game_Files\smapi-internal\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="xTile">
      <HintPath>C:\Users\User\Desktop\SDVport Version\Game_Files\xTile.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
